### ISSUE TITLE
Create documentation websites

### ISSUE THREAD

**Issue by lamhieu-vk** [nuz-app/nuz#11]
Todos
- [x] Setup with `docusaurus`
- [x] Hosted by `now` or `gh-pages`
- [x] Update websites info
- [ ] Update document
  - [ ] Update contributing information #1
  - [ ] Update workflow document #2
  - [ ] Document for cli #5
  - [ ] Document for registry #6
  - [ ] Document for core #7
